name: Tests

on: [push]

jobs:
  phpunit:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - uses: php-actions/composer@v6

      - name: PHPUnit Tests
        uses: php-actions/phpunit@master
        env:
          TEST_NAME: Scarlett
          XDEBUG_MODE: coverage
        with:
          version: 9.6
          bootstrap: vendor/autoload.php
          configuration: phpunit.xml
          php_extensions: "xdebug"
          args: --coverage-text
